# Generated by Django 5.1 on 2024-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10),
        ),
    ]
